TrainTable/TrainTable.UI/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TrainTable.BLL.Services.Interfaces;
using TrainTable.DAL.Models;
using TrainTable.UI.Models;
using TrainTable.UI.Models.Home;
using WebUI.Models;

namespace TrainTable.UI.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IService<Train> _trainService;
        private readonly IService<City> _cityService;
        private readonly IService<FavoriteTrain> _favoriteTrainService;
        private readonly UserManager<User> _userManager;

        public FavoritesController(ILogger<HomeController> logger,
            IService<Train> trainService,
            IService<City> cityService,
            UserManager<User> userManager,
            IService<FavoriteTrain> favoriteTrainService)
        {
            _logger = logger;
            _trainService = trainService;
            _cityService = cityService;
            _userManager = userManager;
            _favoriteTrainService = favoriteTrainService;
        }


        public async Task<IActionResult> Favorites()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var favsId = _favoriteTrainService.ReadAll().Where(i => i.UserId == user.Id).Select(x => x.Id);
            if (!favsId.Any())
            {
                var list1 = new List<TrainInfo>();

                return View(list1);
            }

            var routes = _trainService.ReadAll().Where(x => favsId.Contains(x.Id));
            var list = new List<TrainInfo>();
            foreach (var route in routes)
            {
                var cityFrom = await _cityService.ReadById(route.DepartureId);
                var cityTo = await _cityService.ReadById(route.DestinationId);

                list.Add(new TrainInfo
                {
                    Departure = cityFrom.Name,
                    DepertureTime = route.DepartureTime,
                    Destination = cityTo.Name,
                    DestinationTime = route.DestinationTime,
                    Id = route.Id,
                    Name = route.Name,
                    Type = route.TypeId,
                    Time = route.DepartureTime.Subtract(route.DestinationTime),
                });
            }

            return View(list);
        }
    }
}

TrainTable/TrainTable.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainTable.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrainTable.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Manager"))
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li><a asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                <li><a asp-area="" asp-controller="Manager" asp-action="StatisticsOne"> Статистика</a></li>
                                <li><a asp-area="" asp-controller="Manager" asp-action="Index"> Управление базой</a></li>
                                <li><a asp-area="" asp-controller="UserManager" asp-action="Index"> Управление аккаунтами</a></li>

                            </ul>
                        }
                        @if (User.IsInRole("User"))
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li><a asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                <li><a asp-controller="Favorites" asp-action="Favorites">Израбнные поезда</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="Profile"> Профиль</a></li>
                            </ul>
                        }
                        @if (User.IsInRole("Operator"))
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li><a asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                <li><a asp-area="" asp-controller="Order" asp-action="Index"> Профиль</a></li>
                            </ul>
                        }
                        @if (User.IsInRole("Driver"))
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li><a asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                <li><a asp-area="" asp-controller="Driver" asp-action="Index"> Профиль</a></li>
                            </ul>
                        }

                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a asp-controller="Account" asp-action="Register"><span class="glyphicon glyphicon-user"></span> Зарегистироваться</a></li>
                            <li><a asp-area="" asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TrainTable.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>